server:
  port: 80

spring:
  application:
    name: akww-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8

mybatis-plus:
  tenant-enable: true
  mapper-locations: classpath:/mapper/mysql/*.xml
  global-config:
    banner: false
    db-config:
      field-strategy: NOT_EMPTY
  type-handlers-package: com.akww.hello.world.mapper

logging:
  level:
    com.akww.hello.world.mapper : debug

swagger:
  enable: true
